# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 1997 - July 2008 CWI, August 2008 - 2016 MonetDB B.V.

## Process this file with automake to produce Makefile.in

INCLUDES = .. ../include ../storage \
                   ../../../jkd_master/src/include \
                   ../../common/jkdbase/include \
		   ../common \
                   ../backends/monet5 \
                   ../../common/options \
                   ../../common/stream \
                   ../../common/tracelog \
                   ../../monetdb5/mal \
                   ../../monetdb5/modules/atoms \
                   ../../monetdb5/modules/kernel \
                   ../../monetdb5/mal \
                   ../../monetdb5/modules/mal \
                   ../../monetdb5/optimizer \
                   ../../monetdb5/scheduler \
                   ../../monetdb5/extras/rapi \
		   ../../sql/server \
                   ../../gdk

lib_dtm = {
        NOINST
        DIR = libdir
        SOURCES = \
                sql_dtm.c
}
